$(document).ready(function() {
  $(".link_spaceships").click(function() {
    $.ajax({
      type: "POST", //execute ajax
        url: '../include/getResUser.php',
        data: {action: "getID"},
      success: function(fetchedUserID) {
        let userID = fetchedUserID;
        $(".payment_pack_container").html('<div class="payment_pack" id="12"><h3>Hornet Nest pack</h3><span>Price: 10€</span><p>This nest is indeed full of hornets! By purchasing this package you will recieve 200 Hornets!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="8T7U9FU75RHMG"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
        $(".payment_pack_container").append('<div class="payment_pack" id="13"><h3>Spacefire pack</h3><span>Price: 10€</span><p>Fire in space? Only with spacefires! By purchasing this package you will recieve 160 Spacefires!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="2HXAN3LXB5CKE"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
        $(".payment_pack_container").append('<div class="payment_pack" id="14"><h3>Starhawk pack</h3><span>Price: 10€</span><p>Starhawk, named after the Hawk , is indeed hunter of the smaller birds even in spacesabres universe! By purchasing this pack, you will recieve 120 Starhawks!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="A5PKX2Z5YT5N8"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
        $(".payment_pack_container").append('<div class="payment_pack" id="15"><h3>Peacemaker pack</h3><span>Price: 10€</span><p>Had enough of all the conflict around you? Well then this pack is made right for you! By purchasing this pack, you will recieve 40 Peacemaker cruisers!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="G8K9FP2LJ2AKJ"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
        $(".payment_pack_container").append('<div class="payment_pack" id="16"><h3>Centurion pack</h3><span>Price: 10€</span><p>As other military vehicles named Centurion in the past , this one does follow their success line too! By purchasing this pack, you will recieve 40 Centurion cruisers!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="46SGN89MBYUP2"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
  }
  });
});
  $(".link_currencies").click(function() {
    $.ajax({
      type: "POST", //execute ajax
        url: '../include/getResUser.php',
        data: {action: "getID"},
      success: function(fetchedUserID) {
        let userID = fetchedUserID;
        $(".payment_pack_container").html(' <div class="payment_pack" id="1"><h3>Starter credit pack</h3><span>Price: 5€</span><p>This pack contains 2 500 000 Credits, it\'s not much, but it will get you couple of good old hornets in the shipyards.</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="BDK3PVRU4RZH8"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
        $(".payment_pack_container").append(' <div class="payment_pack" id="2"><h3>Credit pack M</h3><span>Price: 10€</span><p>This pack contains 5 750 000 Credits, giving you 15% more in total compared to starter credit pack!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="RFF55LZXZS3X4"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
        $(".payment_pack_container").append(' <div class="payment_pack" id="3"><h3>Credit pack L</h3><span>Price: 25€</span><p>This pack contains 14 400 000 Credits, giving you 20% more in total compared to starter credit pack!</p> <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="AZBMYZCQUFV4A"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div> ');
        $(".payment_pack_container").append(' <div class="payment_pack" id="4"><h3>Credit pack XL</h3><span>Price: 50€</span><p>This pack contains 32 500 000 Credits, giving you 30% more in total compared to starter credit pack!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="5YRGYERG3Z3WL"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div> ');
        $(".payment_pack_container").append(' <div class="payment_pack" id="5"><h3>Credit pack XXL</h3><span>Price: 100€</span><p>This pack contains 75 000 000 Credits, giving you 50% more in total compared to starter credit pack!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="YAAPYGWSFVPHG"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div> ');
        $(".payment_pack_container").append(' <div class="payment_pack" id="6"><h3>Starter hyperid pack</h3><span>Price: 5€</span><p>This pack contains 500 000 Hyperids, enough for some dreadful cruisers!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="2HMZ4QRQVBJDG"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div> ');
        $(".payment_pack_container").append(' <div class="payment_pack" id="7"><h3>Hyperid pack M</h3><span>Price: 10€</span><p>This pack contains 1 150 000 Hyperids, that\'s 15% more than hyperid starter pack!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="KPKF48TWP6K9Y"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div> ');
        $(".payment_pack_container").append(' <div class="payment_pack" id="8"><h3>Hyperid pack L</h3><span>Price: 25€</span><p>This pack contains 2 880 000 Hyperids, giving you 20% more than the hyperid starter pack!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="6FMVMUDBDGREU"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div> ');
        $(".payment_pack_container").append('<div class="payment_pack" id="9"><h3>Hyperid pack XL</h3><span>Price: 50€</span><p>This pack contains 6 500 000 Hyperids, giving you 30% more than the hyperid starter pack!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="YPZUFAMN25WMN"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div> ');
        $(".payment_pack_container").append(' <div class="payment_pack" id="10"><h3>Hyperid pack XXL</h3><span>Price: 100€</span><p>This pack contains 15 000 000 Hyperids,  giving you 50% more than the hyperid starter pack!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="QPU8BFTRDCRSG"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div> ');
        $(".payment_pack_container").append('<div class="payment_pack" id="11"><h3>Natium pack</h3><span>Price: 10€</span><p>This pack contains 5000 units of the rarest resource "Natium", which is used in Na-Thalis destroyer and M-RS01 production.</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="VXZ65FLM243R6"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div> ');
  }
  });
  });
  $(".link_bundles").click(function() {
    $.ajax({
      type: "POST", //execute ajax
        url: '../include/getResUser.php',
        data: {action: "getID"},
      success: function(fetchedUserID) {
        let userID = fetchedUserID;
        $(".payment_pack_container").html(' <div class="payment_pack" id="17"><h3>Bounty hunter bundle</h3><span>Price: 5€</span><p>This bundle contains 400 000 credits, 80 000 hyperids, 60 Hornets and 10 000 units of fuel!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="YR8QZJT65EXK4"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
        $(".payment_pack_container").append(' <div class="payment_pack" id="18"><h3>Captain bundle</h3><span>Price: 15€</span><p>By purchasing this bundle, you will recieve 100 Hornets, 100 Spacefires and 20 Starhawks!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="GEHP5PKDE7JTG"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
        $(".payment_pack_container").append(' <div class="payment_pack" id="19"><h3>Brigadier General bundle</h3><span>Price: 30€</span><p>This bundle contains 2 000 000 credits, 50 Peacemakers and 40 Starhawks!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="9AWA7FMKA8KD6"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
        $(".payment_pack_container").append(' <div class="payment_pack" id="20"><h3>Hand of Midas bundle</h3><span>Price: 30€</span><p>By purchasing this bundle, you will recieve 7 000 000 Credits and 1 500 000 Hyperids!</p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="BWEJX8HNU4QPA"><input type="hidden" name="custom" value="'+userID+'"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form></div>');
  }
  });
});
});
